services:
  - type: web
    name: onekeel-swarm
    env: node
    plan: starter
    buildCommand: NPM_CONFIG_PRODUCTION=false npm ci && npm run build:render
    preDeployCommand: npm run db:push
    startCommand: npm start
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_AUTH
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: onekeel-postgres
          property: connectionString
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        value: mg.watchdogai.us
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SUPERMEMORY_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DISABLE_AUTO_RESPONSES
        sync: false
      - key: IMAP_HOST
        value: imap.gmail.com
      - key: IMAP_USER
        sync: false
      - key: IMAP_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: onekeel-redis
          property: connectionString
    healthCheckPath: /api/health

  - type: redis
    name: onekeel-redis
    plan: starter

databases:
  - name: onekeel-postgres
    databaseName: onekeel_swarm
    user: onekeel_user
    plan: starter