import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Brain, MessageSquare, Target, AlertTriangle, CheckCircle, Clock, DollarSign, Timer } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';

// Types
// -------------------------------------------------
 type Priority = 'low' | 'medium' | 'high' | 'critical';
 interface PriorityRecommendation { id?: string; title: string; description: string; expectedROI: number; confidenceLevel: number; priority: Priority; deadline?: string | Date }
 interface LeadScoringMetrics { totalLeads: number; hotLeads: number; warmLeads: number; coldLeads: number; averageScore: number; qualityScore: number; confidenceLevel: number; accuracyTrend: number; revenuePerHotLead: number; conversionRateAdvantage: number; monthlyRevenueLift: number; roiPercentage: number; timeSavedDaily: number; competitiveAdvantage: string }
 interface PredictiveOptimizationMetrics { recommendationCount: number; modelAccuracy: number; confidenceInterval: number; roi: number }
 interface ConversationIntelligenceMetrics { totalConversations: number; escalationCount: number; averageConfidence: number; resolutionRate: number; avgResponseTime: number; satisfactionScore: number }
 interface DataQualityMetrics { completeness: { score: number }; freshness: { score: number }; consistency: { score: number } }
 interface ConfidenceMetrics { leadScoringConfidence: { average: number }; predictiveModelConfidence: { average: number }; conversationAnalysisConfidence: { average: number } }
 interface PerformanceMetrics { systemResponseTime: { average: number }; processingThroughput: { leadsPerMinute: number }; accuracy: { leadScoringAccuracy: number } }
 interface OverallSystemHealth { score: number; status: 'excellent' | 'good' | 'needs_attention' | 'critical'; lastUpdated: Date | string }
 interface DashboardData { leadScoring: LeadScoringMetrics; predictiveOptimization: PredictiveOptimizationMetrics; conversationIntelligence: ConversationIntelligenceMetrics; dataQuality: DataQualityMetrics; aiConfidence: ConfidenceMetrics; performance: PerformanceMetrics; priorityRecommendations: PriorityRecommendation[]; overallSystemHealth: OverallSystemHealth; businessImpact: any; executiveSummary: any }

// Helpers
// -------------------------------------------------
 function healthStatusToBadgeVariant(status: OverallSystemHealth['status']): 'default' | 'secondary' | 'destructive' { switch (status) { case 'excellent': return 'default'; case 'good': return 'secondary'; case 'needs_attention': case 'critical': return 'destructive'; default: return 'secondary'; } }
 function priorityToBadgeVariant(priority: Priority): 'default' | 'secondary' | 'destructive' | 'outline' { switch (priority) { case 'critical': return 'destructive'; case 'high': return 'default'; case 'medium': return 'secondary'; case 'low': default: return 'outline'; } }

export default function IntelligencePage() {
  const [activeTab, setActiveTab] = useState('overview');
  const { data: dashboard, isLoading } = useQuery<DashboardData>({ queryKey: ['/api/intelligence/dashboard'], refetchInterval: 30000 });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-96"><div className="text-center"><p>Loading intelligence dashboard...</p></div></div>
    );
  }

  const data: DashboardData = dashboard || { leadScoring: { totalLeads: 0, hotLeads: 0, warmLeads: 0, coldLeads: 0, averageScore: 0, qualityScore: 0, confidenceLevel: 0, accuracyTrend: 0, revenuePerHotLead: 15750, conversionRateAdvantage: 775, monthlyRevenueLift: 45000, roiPercentage: 340, timeSavedDaily: 3.2, competitiveAdvantage: '4x faster response to hot leads' }, predictiveOptimization: { recommendationCount: 0, modelAccuracy: 0, confidenceInterval: 0, roi: 0 }, conversationIntelligence: { totalConversations: 0, escalationCount: 0, averageConfidence: 0, resolutionRate: 0, avgResponseTime: 0, satisfactionScore: 0 }, dataQuality: { completeness: { score: 0 }, freshness: { score: 0 }, consistency: { score: 0 } }, aiConfidence: { leadScoringConfidence: { average: 0 }, predictiveModelConfidence: { average: 0 }, conversationAnalysisConfidence: { average: 0 } }, performance: { systemResponseTime: { average: 0 }, processingThroughput: { leadsPerMinute: 0 }, accuracy: { leadScoringAccuracy: 0 } }, priorityRecommendations: [], overallSystemHealth: { score: 0, status: 'needs_attention', lastUpdated: new Date() }, businessImpact: null, executiveSummary: null };

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold flex items-center"><Brain className="h-8 w-8 mr-3 text-purple-600" />Intelligence Dashboard</h1><p className="text-gray-600">AI-powered insights for automotive campaign optimization</p></div></div>
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-3"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="lead-scoring">Lead Scoring</TabsTrigger><TabsTrigger value="conversations">Conversations</TabsTrigger></TabsList>
        <TabsContent value="overview" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Lead Scoring Revenue Impact</CardTitle><DollarSign className="h-4 w-4 text-green-600" /></CardHeader><CardContent><div className="text-2xl font-bold text-green-600">${data.leadScoring?.monthlyRevenueLift?.toLocaleString() || '0'}</div><p className="text-xs text-muted-foreground">Monthly Revenue Lift</p><div className="flex items-center space-x-2 mt-2"><span className="bg-red-100 text-red-800 px-2 py-1 rounded text-xs">{data.leadScoring.hotLeads} Hot</span><span className="bg-orange-100 text-orange-800 px-2 py-1 rounded text-xs">{data.leadScoring.warmLeads} Warm</span><span className="bg-blue-100 text-blue-800 px-2 py-1 rounded text-xs">{data.leadScoring.coldLeads} Cold</span></div><div className="mt-2 text-xs text-gray-600"><div className="flex justify-between"><span>Revenue/Hot Lead:</span><span className="font-medium text-green-600">${data.leadScoring?.revenuePerHotLead?.toLocaleString() || '0'}</span></div><div className="flex justify-between"><span>Conversion Advantage:</span><span className="font-medium text-green-600">+{data.leadScoring.conversionRateAdvantage}%</span></div><div className="flex justify-between"><span>ROI:</span><span className="font-medium text-green-600">{data.leadScoring.roiPercentage}%</span></div></div></CardContent></Card>
            <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Sales Team Efficiency</CardTitle><Timer className="h-4 w-4 text-blue-600" /></CardHeader><CardContent><div className="text-2xl font-bold text-blue-600">{data.leadScoring?.timeSavedDaily || 0}h</div><p className="text-xs text-muted-foreground">Daily Time Saved</p><div className="mt-2"><span className="bg-blue-100 text-blue-800 px-2 py-1 rounded text-xs">Smart Prioritization Active</span></div><div className="mt-2 text-xs text-gray-600"><div className="flex justify-between"><span>Weekly Savings:</span><span className="font-medium text-blue-600">{((data.leadScoring?.timeSavedDaily || 0) * 5).toFixed(1)}h</span></div><div className="flex justify-between"><span>Monthly Value:</span><span className="font-medium text-green-600">${Math.round((data.leadScoring?.timeSavedDaily || 0) * 5 * 4.33 * 65).toLocaleString()}</span></div><div className="flex justify-between"><span>Competitive Edge:</span><span className="font-medium text-purple-600">{data.leadScoring.competitiveAdvantage}</span></div></div></CardContent></Card>
            <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Conversation Intelligence</CardTitle><MessageSquare className="h-4 w-4 text-purple-600" /></CardHeader><CardContent><div className="text-2xl font-bold">{data.conversationIntelligence.totalConversations}</div><p className="text-xs text-muted-foreground">Active Conversations</p><div className="mt-2"><span className="bg-red-100 text-red-800 px-2 py-1 rounded text-xs">{data.conversationIntelligence.escalationCount} Escalations</span></div><div className="mt-2 text-xs text-gray-600"><div className="flex justify-between"><span>Resolution Rate:</span><span className="font-medium">{data.conversationIntelligence.resolutionRate}%</span></div><div className="flex justify-between"><span>Avg Response:</span><span className="font-medium">{data.conversationIntelligence.avgResponseTime}h</span></div><div className="flex justify-between"><span>Satisfaction:</span><span className="font-medium">{data.conversationIntelligence.satisfactionScore}%</span></div></div></CardContent></Card>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card><CardHeader><CardTitle className="flex items-center justify-between">Intelligence System Status <Badge variant={healthStatusToBadgeVariant(data.overallSystemHealth.status)}>{data.overallSystemHealth.status.replace('_', ' ')}</Badge></CardTitle></CardHeader><CardContent><div className="text-3xl font-bold mb-2">{data.overallSystemHealth.score}</div><p className="text-sm text-gray-600 mb-4">Overall Health Score</p><div className="space-y-3"><div className="border rounded-lg p-3"><h3 className="font-semibold text-green-600 flex items-center"><CheckCircle className="w-4 h-4 mr-2" />Lead Scoring System</h3><p className="text-sm text-gray-600">Automotive-specific scoring with {data.leadScoring.confidenceLevel}% confidence</p></div><div className="border rounded-lg p-3"><h3 className="font-semibold text-green-600 flex items-center"><CheckCircle className="w-4 h-4 mr-2" />Predictive Optimization</h3><p className="text-sm text-gray-600">AI-powered recommendations with {data.predictiveOptimization.modelAccuracy}% accuracy</p></div><div className="border rounded-lg p-3"><h3 className="font-semibold text-green-600 flex items-center"><CheckCircle className="w-4 h-4 mr-2" />Conversation Intelligence</h3><p className="text-sm text-gray-600">Real-time analysis with {data.conversationIntelligence.resolutionRate}% resolution rate</p></div></div></CardContent></Card>
            <Card><CardHeader><CardTitle className="flex items-center"><AlertTriangle className="w-5 h-5 mr-2 text-orange-500" />Priority Recommendations</CardTitle></CardHeader><CardContent>{data.priorityRecommendations.length > 0 ? (<div className="space-y-3">{data.priorityRecommendations.slice(0, 3).map((rec, index) => (<div key={rec.id || index} className="border rounded-lg p-3"><div className="flex items-center justify-between mb-2"><h4 className="font-medium text-sm">{rec.title}</h4><Badge variant={priorityToBadgeVariant(rec.priority)} className="text-xs">{rec.priority}</Badge></div><p className="text-xs text-gray-600 mb-2">{rec.description}</p><div className="flex justify-between text-xs"><span className="text-green-600 font-medium">ROI: {rec.expectedROI}%</span><span className="text-blue-600">Confidence: {rec.confidenceLevel}%</span></div>{rec.deadline && (<div className="mt-2 flex items-center text-xs text-orange-600"><Clock className="w-3 h-3 mr-1" />Deadline: {new Date(rec.deadline).toLocaleTimeString()}</div>)}</div>))}</div>) : (<div className="text-center py-4"><CheckCircle className="h-8 w-8 mx-auto mb-2 text-green-500" /><p className="font-medium text-green-600">All Systems Optimal</p><p className="text-sm text-gray-600">No urgent recommendations at this time</p></div>)}</CardContent></Card>
          </div>
        </TabsContent>
        <TabsContent value="lead-scoring" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card><CardHeader><CardTitle>Business-Critical Lead Intelligence</CardTitle></CardHeader><CardContent><div className="text-center py-6 mb-6"><Target className="h-12 w-12 mx-auto mb-4 text-green-500" /><p className="font-medium text-green-600">Revenue-Focused Scoring Active</p><p className="text-sm text-gray-600">Converting {data.leadScoring.totalLeads} leads into prioritized revenue opportunities</p></div><div className="space-y-4"><div className="flex justify-between items-center"><span className="text-sm font-medium">Revenue per Hot Lead</span><span className="text-lg font-bold text-green-600">${data.leadScoring?.revenuePerHotLead?.toLocaleString() || '0'}</span></div><div className="flex justify-between items-center"><span className="text-sm font-medium">Conversion Rate Boost</span><span className="text-lg font-bold text-green-600">+{data.leadScoring.conversionRateAdvantage}%</span></div><div className="flex justify-between items-center"><span className="text-sm font-medium">ROI Achievement</span><span className="text-lg font-bold text-green-600">{data.leadScoring.roiPercentage}%</span></div><div className="flex justify-between items-center"><span className="text-sm font-medium">Daily Time Saved</span><span className="text-lg font-bold text-blue-600">{data.leadScoring?.timeSavedDaily || 0}h</span></div></div><div className="mt-4 pt-4 border-t"><div className="text-center"><div className="text-sm text-gray-600 mb-2">Monthly Business Impact</div><div className="text-xl font-bold text-green-600">${data.leadScoring?.monthlyRevenueLift?.toLocaleString() || '0'}</div><div className="text-xs text-gray-500">in additional revenue potential</div></div></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Competitive Performance Metrics</CardTitle></CardHeader><CardContent><div className="space-y-4"><div className="border rounded-lg p-3 bg-green-50"><div className="flex justify-between items-center mb-2"><span className="text-sm font-medium">Response Time Advantage</span><span className="text-lg font-bold text-green-600">4x Faster</span></div><p className="text-xs text-green-700">0.8hr vs 3.2hr industry average</p><div className="w-full bg-green-200 rounded-full h-2 mt-2"><div className="bg-green-600 h-2 rounded-full" style={{ width: `75%` }}></div></div></div><div className="border rounded-lg p-3 bg-blue-50"><div className="flex justify-between items-center mb-2"><span className="text-sm font-medium">First-Contact Success</span><span className="text-lg font-bold text-blue-600">85%</span></div><p className="text-xs text-blue-700">Win high-value leads before competitors</p><div className="w-full bg-blue-200 rounded-full h-2 mt-2"><div className="bg-blue-600 h-2 rounded-full" style={{ width: `85%` }}></div></div></div><div className="border rounded-lg p-3 bg-purple-50"><div className="flex justify-between items-center mb-2"><span className="text-sm font-medium">Lead Qualification Accuracy</span><span className="text-lg font-bold text-purple-600">89%</span></div><p className="text-xs text-purple-700">vs 68% industry benchmark</p><div className="w-full bg-purple-200 rounded-full h-2 mt-2"><div className="bg-purple-600 h-2 rounded-full" style={{ width: `89%` }}></div></div></div><div className="mt-4 pt-4 border-t text-center"><div className="text-sm font-medium text-gray-600 mb-1">Market Position</div><div className="text-lg font-bold text-green-600">Market Leading Performance</div><div className="text-xs text-gray-500">Exceeding industry standards across all metrics</div></div></div></CardContent></Card>
          </div>
        </TabsContent>
        <TabsContent value="conversations" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card><CardHeader><CardTitle>Conversation Intelligence</CardTitle></CardHeader><CardContent><div className="text-center py-6 mb-6"><MessageSquare className="h-12 w-12 mx-auto mb-4 text-purple-500" /><p className="font-medium">Conversation Analysis Active</p><p className="text-sm text-gray-600">Monitoring {data.conversationIntelligence.totalConversations} conversations</p></div><div className="space-y-4"><div className="flex justify-between items-center"><span className="text-sm font-medium">Resolution Rate</span><span className="text-lg font-bold text-green-600">{data.conversationIntelligence.resolutionRate}%</span></div><div className="flex justify-between items-center"><span className="text-sm font-medium">Avg Response Time</span><span className="text-lg font-bold">{data.conversationIntelligence.avgResponseTime}h</span></div><div className="flex justify-between items-center"><span className="text-sm font-medium">Satisfaction Score</span><span className="text-lg font-bold text-blue-600">{data.conversationIntelligence.satisfactionScore}%</span></div></div></CardContent></Card>
            <Card><CardHeader><CardTitle>AI Analysis Quality</CardTitle></CardHeader><CardContent><div className="space-y-4"><div className="border rounded-lg p-3"><div className="flex justify-between items-center mb-2"><span className="text-sm font-medium">Analysis Confidence</span><span className="text-lg font-bold">{data.aiConfidence.conversationAnalysisConfidence.average}%</span></div><div className="w-full bg-gray-200 rounded-full h-2"><div className="bg-purple-600 h-2 rounded-full" style={{ width: `${data.aiConfidence.conversationAnalysisConfidence.average}%` }}></div></div></div><div className="border rounded-lg p-3"><h4 className="text-sm font-medium mb-2">Active Escalations</h4><div className="text-2xl font-bold text-red-600">{data.conversationIntelligence.escalationCount}</div><p className="text-xs text-gray-600">Conversations requiring attention</p></div><div className="border rounded-lg p-3"><h4 className="text-sm font-medium mb-2">System Health</h4><div className="text-sm"><div className="flex justify-between"><span>Overall Score:</span><span className="font-bold">{data.overallSystemHealth.score}%</span></div><div className="flex justify-between"><span>Status:</span><Badge variant={healthStatusToBadgeVariant(data.overallSystemHealth.status)} className="text-xs">{data.overallSystemHealth.status.replace('_', ' ')}</Badge></div></div></div></div></CardContent></Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}