import type { SalesBrief } from './sales-brief-schema';

export function buildHandoverEmail(brief: SalesBrief) {
  const intents = brief.detectedIntents.join(', ') || 'n/a';
  const subject =
    `Handover (${intents}) — ` +
    `${brief.leadEmail ?? brief.leadId} ` +
    `— ${brief.campaignName ?? brief.campaignId}`;

  const transcript = brief.transcript
    .map(m => `[${m.timestamp}] ${m.sender.toUpperCase()}: ${m.content}`)
    .join('\n');

  const text = [
    `Handover Reason: ${brief.handoverReason}`,
    `Detected Intents: ${intents}`,
    `Triggered At: ${brief.triggeredAt}`,
    `Lead: ${brief.leadEmail ?? brief.leadId}`,
    `Campaign: ${brief.campaignName ?? brief.campaignId}`,
    '',
    'Transcript:',
    transcript,
    '',
    '--',
    'Automated handover generated by Campaign AI',
  ].join('\n');

  return { subject, text };
}