name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (when available)
        run: |
          if [ -f "package.json" ] && grep -q '"test"' package.json; then
            npm test
          else
            echo "No tests configured yet"
          fi

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Render
        run: |
          echo "Render.com will automatically deploy from this push to main branch"
          echo "Check your Render dashboard for deployment status"
          echo "Deployment URL: https://onekeel-swarm.onrender.com"

      - name: Health Check (wait for deployment)
        run: |
          echo "Waiting 60 seconds for deployment to complete..."
          sleep 60
          echo "Checking health endpoint..."
          for i in {1..10}; do
            if curl -f https://onekeel-swarm.onrender.com/api/health/system 2>/dev/null; then
              echo "Deployment successful!"
              exit 0
            fi
            echo "Attempt $i failed, waiting 30 seconds..."
            sleep 30
          done
          echo "Health check failed after 10 attempts"
          exit 1
        continue-on-error: true